/**
 * Google Search Console API Integration
 * 
 * This service handles fetching data from Google Search Console API
 * Requires OAuth2 authentication and proper API setup
 */

import type { GoogleSearchMetrics, GoogleSearchQuery, GoogleSearchPage, GoogleSearchConsoleResponse } from "@/lib/types/seo"

interface GoogleSearchConsoleConfig {
  access_token: string
  property_url: string // e.g., "sc-domain:example.com" or "https://example.com"
}

interface SearchAnalyticsParams {
  startDate: string // YYYY-MM-DD
  endDate: string // YYYY-MM-DD
  dimensions?: ("query" | "page" | "country" | "device")[]
  rowLimit?: number
}

/**
 * Fetch search analytics data from Google Search Console
 */
export async function fetchSearchAnalytics(
  config: GoogleSearchConsoleConfig,
  params: SearchAnalyticsParams
): Promise<GoogleSearchConsoleResponse> {
  const { access_token, property_url } = config
  const { startDate, endDate, dimensions = [], rowLimit = 1000 } = params

  const url = new URL(`https://www.googleapis.com/webmasters/v3/sites/${encodeURIComponent(property_url)}/searchAnalytics/query`)
  
  const requestBody = {
    startDate,
    endDate,
    dimensions: dimensions.length > 0 ? dimensions : undefined,
    rowLimit,
  }

  try {
    const response = await fetch(url.toString(), {
      method: "POST",
      headers: {
        Authorization: `Bearer ${access_token}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify(requestBody),
    })

    if (!response.ok) {
      const error = await response.json()
      throw new Error(`Google Search Console API error: ${error.error?.message || response.statusText}`)
    }

    return await response.json()
  } catch (error) {
    console.error("Error fetching Google Search Console data:", error)
    throw error
  }
}

/**
 * Transform Google Search Console API response to our metrics format
 */
export function transformSearchAnalytics(
  data: GoogleSearchConsoleResponse,
  websiteId: string,
  date: string
): GoogleSearchMetrics {
  const totalClicks = data.rows.reduce((sum, row) => sum + row.clicks, 0)
  const totalImpressions = data.rows.reduce((sum, row) => sum + row.impressions, 0)
  const totalCtr = totalImpressions > 0 ? totalClicks / totalImpressions : 0
  const avgPosition = data.rows.reduce((sum, row) => sum + row.position, 0) / data.rows.length

  return {
    id: "", // Will be generated by database
    website_id: websiteId,
    metric_date: date,
    clicks: totalClicks,
    impressions: totalImpressions,
    ctr: totalCtr,
    average_position: avgPosition,
    created_at: new Date().toISOString(),
  }
}

/**
 * Fetch queries data (top performing search queries)
 */
export async function fetchQueries(
  config: GoogleSearchConsoleConfig,
  startDate: string,
  endDate: string,
  limit: number = 100
): Promise<GoogleSearchQuery[]> {
  const response = await fetchSearchAnalytics(config, {
    startDate,
    endDate,
    dimensions: ["query"],
    rowLimit: limit,
  })

  return response.rows.map((row) => ({
    id: "",
    website_id: "", // Will be set by caller
    query: row.keys[0],
    clicks: row.clicks,
    impressions: row.impressions,
    ctr: row.ctr,
    average_position: row.position,
    metric_date: endDate,
    created_at: new Date().toISOString(),
  }))
}

/**
 * Fetch pages data (top performing pages)
 */
export async function fetchPages(
  config: GoogleSearchConsoleConfig,
  startDate: string,
  endDate: string,
  limit: number = 100
): Promise<GoogleSearchPage[]> {
  const response = await fetchSearchAnalytics(config, {
    startDate,
    endDate,
    dimensions: ["page"],
    rowLimit: limit,
  })

  return response.rows.map((row) => ({
    id: "",
    website_id: "", // Will be set by caller
    page_url: row.keys[0],
    clicks: row.clicks,
    impressions: row.impressions,
    ctr: row.ctr,
    average_position: row.position,
    metric_date: endDate,
    created_at: new Date().toISOString(),
  }))
}

/**
 * Refresh OAuth token (if using OAuth2)
 */
export async function refreshAccessToken(refreshToken: string, clientId: string, clientSecret: string): Promise<string> {
  const response = await fetch("https://oauth2.googleapis.com/token", {
    method: "POST",
    headers: {
      "Content-Type": "application/x-www-form-urlencoded",
    },
    body: new URLSearchParams({
      client_id: clientId,
      client_secret: clientSecret,
      refresh_token: refreshToken,
      grant_type: "refresh_token",
    }),
  })

  if (!response.ok) {
    throw new Error("Failed to refresh Google OAuth token")
  }

  const data = await response.json()
  return data.access_token
}

// Mock data for development/testing
export function getMockGoogleSearchMetrics(websiteId: string, date: string): GoogleSearchMetrics {
  return {
    id: `mock-${Date.now()}`,
    website_id: websiteId,
    metric_date: date,
    clicks: Math.floor(Math.random() * 5000) + 1000,
    impressions: Math.floor(Math.random() * 50000) + 10000,
    ctr: Math.random() * 0.1 + 0.02,
    average_position: Math.random() * 20 + 5,
    created_at: new Date().toISOString(),
  }
}

interface GoogleSearchConsoleResponse {
  rows: Array<{
    keys: string[]
    clicks: number
    impressions: number
    ctr: number
    position: number
  }>
}
